apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-10T15:18:31Z"
  name: currency-conversion
  namespace: default
  resourceVersion: "106597"
  selfLink: /api/v1/namespaces/default/configmaps/currency-conversion
  uid: b8406823-5e5f-4d5c-8cfc-0d37e5ba22a3
