version: '3.7'

services:
  naming-server:
    image: viferpar/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
      
  api-gateway:
    image: viferpar/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:   
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
      spring.zipkin.base-url: http://zipkin-server:9411
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
  
  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always  
  
  rabbitmq:
    image: rabbitmq:3.8.14-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network    
  
  currency-exchange:
    image: viferpar/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:   
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
      spring.zipkin.base-url: http://zipkin-server:9411
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
  
  currency-conversion:
    image: viferpar/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:   
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
      spring.zipkin.base-url: http://zipkin-server:9411
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

networks:
  currency-network:
